# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import rate.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pupper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('picture', models.ImageField(upload_to=rate.models.get_image_path)),
                ('score', models.IntegerField(default=1400)),
            ],
        ),
    ]
